[package]
name = "pico-tts"
version = "0.1.0"
edition = "2024"
authors = ["Raph Levien <raph.levien@gmail.com>"]
license = "Apache-2.0 OR MIT"

[dependencies]
bitflags = "2.10.0"
clap = { version = "4.5.51", features = ["derive"] }
hound = "3.5.1"
rpoly = { version = "0.2.9", optional = true }
